### ISSUE TITLE
trigger fun <None>

### ISSUE THREAD

**Issue by leafi** [DiscoBizzle/Ghost-Simulator#3]
changing trigger result fun to < None >:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/local/lib/python2.7/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
    result = f(py_self, *args)
  File "/usr/local/lib/python2.7/site-packages/pyglet/window/cocoa/pyglet_view.py", line 245, in mouseDown_
    self._window.dispatch_event('on_mouse_press', x, y, buttons, modifiers)
  File "/usr/local/lib/python2.7/site-packages/pyglet/window/__init__.py", line 1155, in dispatch_event
    if EventDispatcher.dispatch_event(self, _args) != False:
  File "/usr/local/lib/python2.7/site-packages/pyglet/event.py", line 358, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/site-packages/pyglet/event.py", line 355, in dispatch_event
    if handler(_args):
  File "/Users/leaf/Ghost-Simulator/gslib/mouse.py", line 29, in on_mouse_press
    self.mouse_click((x, y), 'down', button)
  File "/Users/leaf/Ghost-Simulator/gslib/mouse.py", line 44, in mouse_click
    self.check_list_event(pos, typ, button)
  File "/Users/leaf/Ghost-Simulator/gslib/mouse.py", line 144, in check_list_event
    if to_click.handle_event(pos, typ, button):
  File "/Users/leaf/Ghost-Simulator/gslib/drop_down_list.py", line 132, in handle_event
    return self.check_clicked(pos)
  File "/Users/leaf/Ghost-Simulator/gslib/drop_down_list.py", line 166, in check_clicked
    if b.check_clicked(click_pos):
  File "/Users/leaf/Ghost-Simulator/gslib/button.py", line 174, in check_clicked
    self.perf_function()
  File "/Users/leaf/Ghost-Simulator/gslib/button.py", line 191, in perf_function
    self.function()
  File "/Users/leaf/Ghost-Simulator/gslib/drop_down_list.py", line 26, in func
    owner.function()
  File "/Users/leaf/Ghost-Simulator/gslib/map_edit.py", line 500, in add_action_to_trigger
    trig.add_action(self.drop_lists['add_actions'].selected)
  File "/Users/leaf/Ghost-Simulator/gslib/triggers.py", line 45, in add_action
    func.append(action(self.objects[-1])) # last object is Target
TypeError: 'NoneType' object is not callable

**Comment by MartinHowarth** [comment]
Fixed.
